name: Diplomacy
main: me.tedwoodworth.diplomacy.Diplomacy
version: 0.1.0

commands:
  plot:
    description: Manage a plot.
    aliases: [p]
    usage: "Usage: /<command> ..."

  nation:
    description: Manage a nation.
    aliases: [n]
    usage: "Usage: /<command> ..."

  group:
    description: Manage a group.
    aliases: [g]
    usage: "Usage: /<command> ..."
